### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by unicornbetrayal** [BluCobalt/SFMaven#1]
bri'ish people declaring variables in php be like £poop;

**Comment by BluCobalt** [comment]
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

**Comment by BluCobalt** [comment]
github please turn closed back to red and keep purple for merged 😊

**Comment by unicornbetrayal** [comment]
I love the GitHub mobile app
